### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by tosiran** [tosiran/chat-space#12]
#IP アドレス
54.178.169.19

**Comment by chiii220** [comment]
松下さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○文字色を模範通りにしましょう。
<img width="1431" alt="ChatSpace" src="https://user-images.githubusercontent.com/55054853/77736373-77a12c00-704f-11ea-8a1d-05100f961ad7.png">

○グループ名とメッセージに青い下線があるので消しましょう
<img width="191" alt="ChatSpace" src="https://user-images.githubusercontent.com/55054853/77736607-db2b5980-704f-11ea-83f1-f85ca102937f.png">


○メンバー名の前に「Member:」の表記がない
<img width="310" alt="ChatSpace" src="https://user-images.githubusercontent.com/55054853/77736571-c949b680-704f-11ea-9fda-68308ccb6c6d.png">


※カリキュラムの中にある、模範のchatspaceと仕様書を参考に、修正をお願いします。
[模範のchatpsace]
https://chat-space-sample.herokuapp.com/
[仕様書]
https://tech-master.s3.amazonaws.com/uploads/curriculums//03e925297f3843c603f028b177b4e86b.png

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tosiran** [comment]
修正しました

**Comment by chiii220** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
